Repository Stealth-Robotics/Stealth2023, pull requests merged in 2023-02, with the labels that each got.

#3 Added Base Swerve Code
  .vscode/launch.json
  build.gradle
  simgui-ds.json
  simgui.json
  src/main/java/frc/lib/math/Conversions.java
  src/main/java/frc/lib/util/COTSFalconSwerveConstants.java
  src/main/java/frc/lib/util/CTREModuleState.java
  src/main/java/frc/lib/util/SwerveModuleConstants.java
  src/main/java/frc/robot/CTREConfigs.java
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/RobotMap.java
  src/main/java/frc/robot/commands/FollowPathCommand.java
  src/main/java/frc/robot/commands/TeleopDrivebaseDefaultCommand.java
  src/main/java/frc/robot/subsystems/Swerve/DrivebaseSubsystem.java
  src/main/java/frc/robot/subsystems/Swerve/SwerveModule.java
Labels: drivebase

#21 Added pathplanner paths as well as autos to run them
  .gitignore
  .pathplanner/settings.json
  build.gradle
  src/main/deploy/pathplanner/ preloadParkCenter.path
  src/main/deploy/pathplanner/preloadPlusOneLeft1.path
  src/main/deploy/pathplanner/preloadPlusOneLeft2.path
  src/main/deploy/pathplanner/preloadPlusOneRight1.path
  src/main/deploy/pathplanner/preloadPlusOneRight2.path
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/PhotonVisionCameraWrapper.java
  src/main/java/frc/robot/RobotMap.java
  src/main/java/frc/robot/commands/BluePreloadParkCenter.java
  src/main/java/frc/robot/commands/BluePreloadPlusOneLeft.java
  src/main/java/frc/robot/commands/BluePreloadPlusOneRight.java
  src/main/java/frc/robot/commands/FollowPathCommand.java
  src/main/java/frc/robot/commands/LevelRobot.java
  src/main/java/frc/robot/commands/SwerveTrajectoryFollowCommand.java
  src/main/java/frc/robot/subsystems/Swerve/DrivebaseSubsystem.java
  vendordeps/PathplannerLib.json
  vendordeps/photonlib.json
Labels: autonomous

#23 Added rotator to rotate the telescope
  .SysId/sysid.json
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/RobotMap.java
  src/main/java/frc/robot/commands/RotatorDefaultCommand.java
  src/main/java/frc/robot/subsystems/RotatorSubsystem.java
Labels: arm
